# symfonycasts_reset_password:
#     request_password_repository: App\Repository\ResetPasswordRequestRepository
#     throttle_limit: 900     # 15 minutes entre les demandes
#     lifetime: 3600          # 1 heure pour le token
#     enable_garbage_collection: true



# DEV
symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    throttle_limit: 15     # 1 minute entre les demandes
    lifetime: 86400        # 24 heures pour les tests
    enable_garbage_collection: true
